project_id = "imdldceugiairplylnqq"

[functions.send-payment-reminder]
verify_jwt = false

[functions.generate-smart-routine]
verify_jwt = false

[functions.update-exercise-descriptions]
verify_jwt = false

[functions.weekly-adjustment]
verify_jwt = false
