
-- Seed comprehensive exercise catalog (global exercises)
INSERT INTO public.exercises (name, muscle_group, is_global, description) VALUES
-- CHEST
('Press Banca Plano Barra', 'chest', true, 'Press de banca plano con barra olímpica'),
('Press Banca Inclinado Barra', 'chest', true, 'Press inclinado con barra'),
('Press Banca Declinado Barra', 'chest', true, 'Press declinado con barra'),
('Press Banca Plano Mancuernas', 'chest', true, 'Press plano con mancuernas'),
('Press Banca Inclinado Mancuernas', 'chest', true, 'Press inclinado con mancuernas'),
('Aperturas Planas Mancuernas', 'chest', true, 'Aperturas en banco plano'),
('Aperturas Inclinadas Mancuernas', 'chest', true, 'Aperturas en banco inclinado'),
('Cruces en Polea Alta', 'chest', true, 'Cable crossover desde polea alta'),
('Cruces en Polea Baja', 'chest', true, 'Cable crossover desde polea baja'),
('Fondos en Paralelas (Pecho)', 'chest', true, 'Fondos inclinados hacia adelante'),
('Flexiones de Brazos', 'chest', true, 'Push-ups clásicas'),
('Press en Máquina', 'chest', true, 'Press de pecho en máquina'),
-- BACK
('Dominadas Pronación', 'back', true, 'Pull-ups con agarre prono'),
('Dominadas Supinación', 'back', true, 'Chin-ups con agarre supino'),
('Jalón al Pecho Agarre Ancho', 'back', true, 'Lat pulldown agarre ancho'),
('Jalón al Pecho Agarre Cerrado', 'back', true, 'Lat pulldown agarre cerrado'),
('Remo con Barra', 'back', true, 'Remo con barra inclinado'),
('Remo con Mancuerna', 'back', true, 'Remo unilateral con mancuerna'),
('Remo en Polea Baja', 'back', true, 'Remo sentado en polea'),
('Remo T-Bar', 'back', true, 'Remo con barra T'),
('Peso Muerto Convencional', 'back', true, 'Peso muerto con barra'),
('Peso Muerto Rumano', 'back', true, 'Peso muerto rumano'),
('Pull Over con Mancuerna', 'back', true, 'Pull over en banco plano'),
('Remo en Máquina', 'back', true, 'Remo en máquina Hammer'),
('Hiperextensiones', 'back', true, 'Extensiones lumbares en banco 45°'),
-- SHOULDERS
('Press Militar Barra', 'shoulders', true, 'Press de hombros con barra de pie'),
('Press Militar Mancuernas', 'shoulders', true, 'Press de hombros sentado con mancuernas'),
('Press Arnold', 'shoulders', true, 'Press Arnold con mancuernas'),
('Elevaciones Laterales Mancuernas', 'shoulders', true, 'Elevaciones laterales con mancuernas'),
('Elevaciones Laterales en Polea', 'shoulders', true, 'Elevaciones laterales con polea'),
('Elevaciones Frontales', 'shoulders', true, 'Elevaciones frontales con mancuernas'),
('Pájaros (Deltoides Posterior)', 'shoulders', true, 'Reverse fly con mancuernas'),
('Face Pulls', 'shoulders', true, 'Face pulls con cuerda en polea'),
('Encogimientos de Hombros', 'shoulders', true, 'Shrugs con mancuernas o barra'),
('Press en Máquina Hombros', 'shoulders', true, 'Press de hombros en máquina'),
-- BICEPS
('Curl con Barra Recta', 'biceps', true, 'Curl de bíceps con barra recta'),
('Curl con Barra Z', 'biceps', true, 'Curl de bíceps con barra Z'),
('Curl con Mancuernas Alterno', 'biceps', true, 'Curl alterno con mancuernas'),
('Curl Martillo', 'biceps', true, 'Curl martillo con mancuernas'),
('Curl Concentrado', 'biceps', true, 'Curl concentrado sentado'),
('Curl en Banco Scott', 'biceps', true, 'Curl predicador en banco Scott'),
('Curl en Polea Baja', 'biceps', true, 'Curl de bíceps en polea baja'),
('Curl Inclinado con Mancuernas', 'biceps', true, 'Curl en banco inclinado'),
-- TRICEPS
('Fondos en Paralelas (Tríceps)', 'triceps', true, 'Fondos con torso erguido'),
('Press Francés con Barra Z', 'triceps', true, 'Skull crushers con barra Z'),
('Extensión de Tríceps en Polea', 'triceps', true, 'Pushdown con cuerda o barra'),
('Extensión de Tríceps con Mancuerna', 'triceps', true, 'Extensión overhead con mancuerna'),
('Patada de Tríceps', 'triceps', true, 'Kickback con mancuerna'),
('Press Cerrado con Barra', 'triceps', true, 'Press banca agarre cerrado'),
('Extensión en Polea Alta con Cuerda', 'triceps', true, 'Tricep pushdown con cuerda'),
('Fondos en Banco', 'triceps', true, 'Dips en banco'),
-- LEGS
('Sentadilla con Barra', 'legs', true, 'Back squat con barra'),
('Sentadilla Frontal', 'legs', true, 'Front squat con barra'),
('Sentadilla Búlgara', 'legs', true, 'Split squat búlgaro'),
('Sentadilla Goblet', 'legs', true, 'Sentadilla con mancuerna o kettlebell'),
('Prensa de Piernas', 'legs', true, 'Leg press 45°'),
('Hack Squat', 'legs', true, 'Sentadilla en máquina hack'),
('Extensión de Cuádriceps', 'legs', true, 'Leg extension en máquina'),
('Curl Femoral Acostado', 'legs', true, 'Leg curl acostado'),
('Curl Femoral Sentado', 'legs', true, 'Leg curl sentado'),
('Peso Muerto Sumo', 'legs', true, 'Peso muerto con agarre sumo'),
('Zancadas con Mancuernas', 'legs', true, 'Lunges caminando con mancuernas'),
('Step Ups', 'legs', true, 'Subidas al cajón con peso'),
('Elevación de Talones de Pie', 'legs', true, 'Calf raise de pie'),
('Elevación de Talones Sentado', 'legs', true, 'Calf raise sentado'),
('Hip Thrust con Barra', 'legs', true, 'Hip thrust con barra'),
('Abducción de Cadera', 'legs', true, 'Abducción en máquina'),
('Aducción de Cadera', 'legs', true, 'Aducción en máquina'),
-- CORE
('Plancha Frontal', 'core', true, 'Plank isométrica frontal'),
('Plancha Lateral', 'core', true, 'Side plank isométrica'),
('Crunch Abdominal', 'core', true, 'Crunch clásico en suelo'),
('Crunch en Polea Alta', 'core', true, 'Cable crunch de rodillas'),
('Elevación de Piernas Colgado', 'core', true, 'Hanging leg raise'),
('Elevación de Piernas en Banco', 'core', true, 'Leg raise acostado'),
('Russian Twist', 'core', true, 'Giros rusos con peso'),
('Ab Wheel Rollout', 'core', true, 'Rueda abdominal'),
('Leñador en Polea (Woodchop)', 'core', true, 'Woodchop en polea'),
('Dead Bug', 'core', true, 'Dead bug controlado'),
-- CARDIO
('Cinta de Correr', 'cardio', true, 'Carrera en cinta'),
('Bicicleta Estática', 'cardio', true, 'Ciclismo en bicicleta fija'),
('Elíptica', 'cardio', true, 'Entrenamiento en elíptica'),
('Remo Ergómetro', 'cardio', true, 'Remo en máquina Concept2'),
('Saltar la Cuerda', 'cardio', true, 'Saltos con cuerda'),
('Escaladora (StairMaster)', 'cardio', true, 'Subida en escaladora'),
('Sprint en Bicicleta Assault', 'cardio', true, 'Sprints en assault bike'),
-- FULL BODY
('Burpees', 'full_body', true, 'Burpees completos'),
('Clean & Press', 'full_body', true, 'Cargada y press con barra'),
('Clean & Jerk', 'full_body', true, 'Cargada y envión olímpico'),
('Snatch', 'full_body', true, 'Arrancada olímpica'),
('Thrusters', 'full_body', true, 'Sentadilla frontal + press'),
('Turkish Get Up', 'full_body', true, 'Levantada turca con kettlebell'),
('Kettlebell Swing', 'full_body', true, 'Swing con kettlebell'),
('Man Makers', 'full_body', true, 'Remo + flexión + squat clean + press'),
('Bear Crawl', 'full_body', true, 'Caminata de oso')
ON CONFLICT DO NOTHING;
