// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imdldceugiairplylnqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZGxkY2V1Z2lhaXJwbHlsbnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3OTA2ODIsImV4cCI6MjA4NzM2NjY4Mn0.YqPzrJ-WT6mLWtzmQnLrQ5-FYEhlzrxTkwxsJg8xGL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});